# sonar.projectKey=inkwell-frontend
# sonar.projectName=InkWell Frontend Web
# sonar.projectVersion=1.0
sonar.projectKey=frontend-web
sonar.projectName=Frontend Web
sonar.projectVersion=1.0

# sonar.sources=src
# sonar.exclusions=**/node_modules/**

sonar.host.url=http://localhost:9000
sonar.token=squ_b3d1ed531ffb7f7ef43db4a3fb1a36b196fb0b75
# Path to source directories
sonar.sources=src
sonar.exclusions=src/**/*.test.jsx,src/**/*.test.js,src/setupTests.js,src/main.jsx,src/__tests__/testHelpers.jsx

# Path to test directories
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript specific
sonar.javascript.lcov.reportPaths=coverage/lcov.info
